---
title: "Real-World Applications of Derivative Estimation (State-Level Covid-19 Case Rates)"
author: "Yikun Zhang"
date: "2023-05-06"
output: html_document
---

This file contains my extended real-world application of the proposed derivative estimator to the state-level COVID-19 case rate data.

```{r}
library(covidcast)
library(modeltools)
library(dplyr)
library(ggplot2)
library(ks)
library(locpol)
library(latex2exp)
library(pspline)

source('derivative_estimation_quotients.R')
```

```{r}
start_day <- "2020-05-01"
end_day <- "2020-12-15"
geo_values <- c("ca", "fl", "ny", "tx", "wa")

case_rates <- suppressMessages(
  covidcast_signal(data_source = "usa-facts",
                   signal = "confirmed_7dav_incidence_prop",
                   start_day = start_day, end_day = end_day,
                   geo_type = "state", geo_values = geo_values))

case_rates$days = difftime(case_rates$time_value, as.Date(start_day), units = "days")
case_rates$day_num = as.numeric(case_rates$days)
summary(case_rates)

```

```{r}
state = "wa"
threshold = 0.5

ggplot(case_rates %>% filter(geo_value == state),
             aes(x = time_value, y = value)) +
  geom_line() +
  labs(x = "Date", y = "Cases per 100,000 people")
```

```{r}
case_rates_sub = case_rates[case_rates$geo_value == state,]
pdf("./Figures/covid_case_raw.pdf", width = 8, height = 6)
par(mar = c(4, 4.8, 0.2, 0.3))  
plot(case_rates_sub$time_value, case_rates_sub$value, xlab = "Date", ylab = "Cases Per 100,000 People", cex.lab=2, cex.axis=2)
lines(case_rates_sub$time_value, case_rates_sub$value, col="black", lwd=3)
```


```{r}
case_rates_sub = case_rates[case_rates$geo_value == state,]

# locpol
dat = data.frame(X = case_rates_sub$day_num, Y = case_rates_sub$value)
Y_locpol2 = locpol(Y ~ X, data = dat, kernel = gaussK, xeval = dat$X, deg = 2)
# Y_locpol3 = locpol(Y ~ X, data = dat, kernel = gaussK, xeval = dat$X, deg = 3)
# Y_locpol4 = locpol(Y ~ X, data = dat, kernel = gaussK, xeval = dat$X, deg = 4)

# pspline
Y_pspline = sm.spline(x = sort(dat$X), y = dat$Y[order(dat$X)], norder = 2)
Y_psp_deriv = predict(Y_pspline, xarg = dat$X, nderiv = 1)

## Proposed estimator
U = kcde(dat$X, eval.points = dat$X, tail.flag = "lower.tail")$estimate
k_opt = OptK(Y = dat$Y, U = U, k_range = NULL, h = NULL, kern = gaussK)
# k_opt = 5
print(k_opt)
deri_est = DerivEstQuotient(Y = dat$Y, X = dat$X, k = k_opt)

h_opt = RSSBandwidth(Y = deri_est$Y_deri, U = deri_est$U_ord, k = k_opt, 
                      h_range = seq(0.001, 0.2, by = 0.001), deg = 3)
print(h_opt)
h_opt = h_opt*1.01431

n = dim(dat)[1]
qry_range = seq(k_opt + 1, n-k_opt, by = 1)
Y_deriv_sm = LocalPolyReg(Y = deri_est$Y_deri, 
                           X = deri_est$U_ord, 
                           xeval = deri_est$U_ord, h = h_opt, 
                           kern = gaussK, deg = 3, deriv_ord = 0)
Y_deriv_trans = Y_deriv_sm * deri_est$den_ord
```


```{r}
ggplot() +
  geom_line(aes(x = case_rates_sub$time_value, y = Y_locpol2$lpFit$Y1), color='blue') +
  geom_line(aes(x = case_rates_sub$time_value, y = Y_psp_deriv), color='orange') +
  geom_line(aes(x = case_rates_sub$time_value, y = Y_deriv_trans), color='red') +
  geom_hline(yintercept = threshold, linetype = 2) +
  labs(x = "Date", y = "Estimated Derivative")
```

```{r}
print(max(Y_deriv_trans))

pdf("./Figures/covid_deriv_com.pdf", width = 8.5, height = 6.3)
par(mar = c(4, 5.5, 0.8, 0.8)) 
plot(case_rates_sub$time_value, Y_deriv_trans, pch=16, xlab = "Date", ylab = TeX("Case Rates Per 100,000 People"), col="red", cex.lab=2, cex.axis=2, cex=0.7, type="l", lwd=4, ylim=c(-7, 5))
lines(x = case_rates_sub$time_value, y = Y_psp_deriv, col="blue", lwd=3)
lines(case_rates_sub$time_value, Y_locpol2$lpFit$Y1, col="orange", lwd=3)
abline(h = max(Y_deriv_trans), col="black", lty="dashed", lwd = 4)
legend("bottomleft", legend=c("Proposed estimator", "Locpol with p=2", "Cubic psplines", "Max rates for the proposed estimator"), fill=c("red", "orange", "blue", "black"), cex=1.5)
```

