---
title: "Simulation 6 (Second-Order Derivative Estimation)"
author: "Yikun Zhang"
date: "2023-05-23"
output: html_document
---

This file reproduces the simulation study 6 and its associated figures (Figure 7b, Figure 8b, 9b) in Liu and De Brabanter (2020).

```{r}
library(ks)
library(locpol)
library(ggplot2)
library(latex2exp)

source('derivative_estimation_quotients.R')
```

```{r}
n = 1000
set.seed(123)
X_5 = runif(n, min = 0, max = 1)
m_5 = 50*exp(-8*(1-2*X_5)^4)*(1-2*X_5)
eps5 = rnorm(n, mean = 0, sd = 2)
Y_5 = m_5 + eps5

pdf("./Figures/sim6_raw_rep.pdf", width = 8, height = 6)
par(mar = c(4, 4.8, 0.2, 0.3))  
plot(X_5, Y_5, xlab = "X", ylab = "Y", cex.lab=2, cex.axis=2)
```

```{r}
U_5 = kcde(X_5, eval.points = X_5, tail.flag = "lower.tail")$estimate
k_opt5 = OptK(Y = Y_5, U = U_5, k_range = seq(1, 300, by = 1), h = NULL, kern = gaussK)
print(k_opt5)
deri_est5 = DerivEstQuotient(Y = Y_5, X = X_5, k = k_opt5)

k_opt_2d5 = OptK1K2(Y = Y_5, U = U_5, k1_range = seq(1, 100, by = 1), k2_range = seq(1, 100, by = 1), h = NULL, kern = gaussK)
# k_opt_2d5 = list("k1" = 44, "k2" = 24)
print(k_opt_2d5)
deri_sec5 = SecondDerivEstQuotient(Y = Y_5, X = X_5, k1 = k_opt_2d5$k1, k2 = k_opt_2d5$k2)

h_opt5 = RSSBandwidth(Y = deri_est5$Y_deri, U = deri_est5$U_ord, k = k_opt3, 
                      h_range = seq(0.05, 0.1, by = 0.005), deg = 3)
print(h_opt5)
h_opt5 = h_opt5*1.01431
h_opt_2d5 = RSSBandwidth(Y = deri_sec5$Y_sec, U = deri_sec5$U_ord, k = k_opt_2d5$k1 + k_opt_2d5$k2, h_range = seq(0.05, 0.1, by = 0.005), deg = 3)
print(h_opt_2d5)
h_opt_2d5 = h_opt_2d5*1.01431

u_qry = seq(min(deri_sec5$U_ord), max(deri_sec5$U_ord), length.out = 100)
True_sec5 = 6400*(1-2*u_qry)^3*exp(-8*(1-2*u_qry)^4)*(32*(1-2*u_qry)^4 - 5)

qry_range = seq(k_opt_2d5$k1 + k_opt_2d5$k2 + 1, 1000 - k_opt_2d5$k1 - k_opt_2d5$k2, by = 1)

Y_deriv_sm5 = LocalPolyReg(Y = deri_est5$Y_deri, X = deri_est5$U_ord, xeval = deri_est5$U_ord, h = h_opt5, kern = gaussK, deg = 3, deriv_ord = 0)
# Y_deriv_sm5 = LocalPolyReg(Y = deri_est5$Y_deri[qry_range], X = deri_est5$U_ord[qry_range], xeval = deri_est5$U_ord, h = h_opt5, kern = gaussK, deg = 3, deriv_ord = 0)
Y_sec_sm5 = LocalPolyReg(Y = deri_sec5$Y_sec, X = deri_sec5$U_ord, xeval = deri_sec5$U_ord, h = h_opt_2d5, kern = gaussK, deg = 3, deriv_ord = 0)
# Y_sec_sm5 = LocalPolyReg(Y = deri_sec5$Y_sec[qry_range], X = deri_sec5$U_ord[qry_range], xeval = deri_sec5$U_ord, h = h_opt_2d5, kern = gaussK, deg = 3, deriv_ord = 0)
```

```{r}
Y_sec_trans5 = Y_sec_sm5 * deri_sec5$den_ord^2 + Y_deriv_sm5 * deri_sec5$den_deriv_ord
Y_sec_raw5 = deri_sec5$Y_sec * deri_sec5$den_ord^2 + deri_est5$Y_deri * deri_sec5$den_deriv_ord

x_qry = seq(min(deri_sec5$X_ord[qry_range]), max(deri_sec5$X_ord[qry_range]), length.out = 100)
True_sec5 = 6400*(1-2*x_qry)^3*exp(-8*(1-2*x_qry)^4)*(32*(1-2*x_qry)^4 - 5)

ggplot() + geom_point(mapping = aes(x = deri_sec5$X_ord[qry_range], y = Y_sec_raw5[qry_range]), size = 0.7, color = "blue") + geom_point(mapping = aes(x = deri_sec5$X_ord[qry_range], y = Y_sec_trans5[qry_range]), size = 1, color = "green") + geom_line(mapping = aes(x = x_qry, y = True_sec5), color = "red", linetype = "dashed", size = 1) + theme_bw(base_size = 22) + xlab("X") + ylab(TeX("$m''(x), \\hat{m}''(x)$"))
```


```{r}
pdf("./Figures/sim6_deriv.pdf", width = 8, height = 6)
par(mar = c(4, 5.5, 0.2, 1))
plot(deri_sec5$X_ord[qry_range], Y_sec_raw5[qry_range], pch=16, xlab = "X", ylab = TeX("$m''(x), \\hat{m}''(x)$"), col="blue", cex.lab=2, cex.axis=2, cex=0.7)
lines(deri_sec5$X_ord[qry_range], y = Y_sec_trans5[qry_range], col="red", lty="dashed", lwd=5)
lines(x_qry, True_sec5, col="black", lwd=5)
legend(0.2, 1900, legend=c(TeX("Noisy $\\hat{m}''(x)$"), TeX("Smoothed $\\hat{m}''(x)$"), TeX("True $m''(x)$")), fill=c("blue", "red", "black"), cex=1.5)
```

```{r}
# locpol
dat5 = data.frame(X = X_5, Y = Y_5)
Y_locpol_sec5 = locpol(Y ~ X, data = dat5, kernel = gaussK, xeval = X_5, deg = 3)

# pspline
Y_pspline_sec5 = sm.spline(x = sort(X_5), y = Y_5[order(X_5)], norder = 2)
Y_psp_deriv_sec5 = predict(Y_pspline_sec5, xarg = X_5, nderiv = 2)

x_qry = seq(min(deri_sec5$X_ord[qry_range])-0.02, max(deri_sec5$X_ord[qry_range])+0.02, length.out = 100)
True_sec5 = 6400*(1-2*x_qry)^3*exp(-8*(1-2*x_qry)^4)*(32*(1-2*x_qry)^4 - 5)

qry_range = seq(k_opt_2d5$k1 + k_opt_2d5$k2 + 1, 1000 - k_opt_2d5$k1 - k_opt_2d5$k2, by = 1)

ggplot() + geom_point(mapping = aes(x = Y_locpol_sec5$lpFit$X, y = Y_locpol_sec5$lpFit$Y2), size = 1, color = "green") + geom_point(mapping = aes(x = X_5, y = Y_psp_deriv_sec5[,1]), size = 0.7, color = "blue") + geom_point(mapping = aes(x = deri_sec5$X_ord, y = Y_sec_trans5), size = 1, color = "red") + geom_line(mapping = aes(x = x_qry, y = True_sec5), color = "black", size = 1) + theme_bw(base_size = 22) + xlab("X") + ylab(TeX("$m(x), \\hat{m}'(x)$")) + xlim(0.05, 0.95)
```

```{r}
a_min = min(X_5)+0.07
a_max = max(X_5) -0.07
pdf("./Figures/sim6_deriv_com.pdf", width = 8, height = 6)
par(mar = c(4, 5.5, 0.6, 1))
plot(deri_sec5$X_ord[(deri_sec5$X_ord > a_min) & (deri_sec5$X_ord < a_max)], Y_sec_trans5[(deri_sec5$X_ord > a_min) & (deri_sec5$X_ord < a_max)], pch=16, xlab = "X", ylab = TeX("$m''(x), \\hat{m}''(x)$"), col="red", cex.lab=2, cex.axis=2, cex=0.7, type="l", lty="dashed", lwd=5, ylim = c(-1600, 1600), xlim = c(0.06,0.94))
lines(Y_locpol_sec5$lpFit$X[(Y_locpol_sec5$lpFit$X > a_min) & (Y_locpol_sec5$lpFit$X< a_max)], Y_locpol_sec5$lpFit$Y2[(Y_locpol_sec5$lpFit$X > a_min) & (Y_locpol_sec5$lpFit$X< a_max)], col="green", lty="dashed", lwd=5)
lines(x_qry, True_sec5, col="black", lwd=5)
legend(0.43, -900, legend=c(TeX("Proposed $\\hat{m}''(x)$"), "locpol3", TeX("True $m''(x)$")), fill=c("red", "green", "black"), cex=1.5)
```

