---
title: "Simulation 1 (First-Order Derivative Estimation)"
author: "Yikun Zhang"
date: "2023-05-18"
output: html_document
---

This file reproduces the simulation study 1 and its associated figures (Figure 1a, 2a, 2b) in Liu and De Brabanter (2020). 

```{r}
library(ks)
library(locpol)
library(ggplot2)
library(latex2exp)

source('derivative_estimation_quotients.R')
```

## Generating the simulated data

```{r}
n = 1000
set.seed(123)
X_1 = runif(n)
m_1 = cos(2*pi*X_1)^2 + log(4/3 + X_1)
eps1 = rnorm(n, mean = 0, sd = 0.1)
Y_1 = m_1 + eps1
dat1 = data.frame(X = X_1, Y = Y_1)
Y_locpol1 = locpol(Y ~ X, data = dat1, kernel = gaussK, xeval = X_1, deg = 3)
```

```{r}
pdf("./Figures/sim1_raw.pdf", width = 8, height = 6)
par(mar = c(4, 4.8, 0.2, 0.3))  
plot(X_1, Y_1, xlab = "X", ylab = "Y", cex.lab=2, cex.axis=2)
lines(sort(X_1), m_1[order(X_1)], col="red", lwd=5)
legend(-0.037, 2.27, legend=c("Raw data", TeX("True function $m(X)$")),
       fill=c("black", "red"), cex=1.5)


pdf("./Figures/sim1_raw_rep.pdf", width = 8, height = 6)
par(mar = c(4, 4.8, 0.2, 0.3))  
plot(X_1, Y_1, xlab = "X", ylab = "Y", cex.lab=2, cex.axis=2)
```

```{r}
U_1 = kcde(X_1, eval.points = X_1, tail.flag = "lower.tail")$estimate
k_opt1 = OptK(Y = Y_1, U = U_1, k_range = seq(1, 499, by = 1), h = NULL, kern = gaussK)
k_opt1 = 26
# print(k_opt1)
deri_est1 = DerivEstQuotient(Y = Y_1, X = X_1, k = k_opt1)

h_opt1 = RSSBandwidth(Y = deri_est1$Y_deri, U = deri_est1$U_ord, k = k_opt1, h_range = seq(0.04, 0.1, by = 0.005), deg = 3)
print(h_opt1)
h_opt1 = h_opt1*1.01431

qry_range = seq(k_opt1 + 1, n-k_opt1, by = 1)
u_qry = seq(min(deri_est1$U_ord[qry_range]), max(deri_est1$U_ord[qry_range]), length.out = 100)
deri_true1 = -2*pi*sin(4*pi*u_qry) + 3/(3*u_qry + 4)

Y_deriv_sm1 = LocalPolyReg(Y = deri_est1$Y_deri, X = deri_est1$U_ord, xeval = deri_est1$U_ord, h = h_opt1, kern = gaussK, deg = 3, deriv_ord = 0)

ggplot() + geom_point(mapping = aes(x = deri_est1$U_ord[qry_range], y = deri_est1$Y_deri[qry_range]), size = 0.7, color = "blue") + geom_line(mapping = aes(x = u_qry, y = deri_true1), color = "red", linetype = "dashed", size = 1) + theme_bw(base_size = 22) + xlab("u") + ylab(TeX("y', $\\hat{r}'(u)$"))
# + geom_point(mapping = aes(x = deri_est1$U_ord[qry_range], y = Y_deriv_sm1[qry_range]), size = 1, color = "green") 
```

```{r}
pdf("./Figures/sim1_deriv_u26.pdf", width = 8.5, height = 6.3)
par(mar = c(4, 6, 0.2, 1))  
plot(deri_est1$U_ord[qry_range], deri_est1$Y_deri[qry_range], col="blue", pch=20, xlab = "U", ylab = TeX("$\\hat{Y}^{(1)}, \\hat{r}^{(1)}(u)$"), cex.lab=2, cex.axis=2)
lines(deri_est1$U_ord[qry_range], y = Y_deriv_sm1[qry_range], col="red", lwd=5, lty="dashed")
legend(-0.01, 9.5, legend=c(TeX("Noisy $\\hat{r}^{(1)}(x)$"), TeX("Smoothed $\\hat{r}^{(1)}(x)$")), fill=c("blue", "red"), cex=1.5)
```


```{r}
Y_deriv_trans1 = Y_deriv_sm1 * deri_est1$den_ord
Y_deriv_noisy1 = deri_est1$Y_deri * deri_est1$den_ord

x_qry = seq(min(deri_est1$X_ord[qry_range]), max(deri_est1$X_ord[qry_range]), length.out = 100)
True_deriv1 = -2*pi*sin(4*pi*x_qry) + 3/(3*x_qry+4)

pdf("./Figures/sim1_deriv_x.pdf", width = 8, height = 6)
par(mar = c(4, 5.5, 0.2, 1))
plot(deri_est1$X_ord[qry_range], Y_deriv_noisy1[qry_range], pch=16, xlab = "X", ylab = TeX("$m'(x), \\hat{m}'(x)$"), col="blue", cex.lab=2, cex.axis=2, cex=0.7)
lines(deri_est1$X_ord[qry_range], Y_deriv_trans1[qry_range], pch=16, col="red", cex=0.7, lty="dashed", lwd=5)
lines(x_qry, True_deriv1, col="black", lwd=5)
legend(-0.03, 9.7, legend=c(TeX("Noisy $\\hat{m}'(x)$"), TeX("Smoothed $\\hat{m}'(x)$"), "True derivative"), fill=c("blue", "red", "black"), cex=1.5)
```


```{r}
U_1 = kcde(X_1, eval.points = X_1, tail.flag = "lower.tail")$estimate
k_opt1 = OptK(Y = Y_1, U = U_1, k_range = seq(1, 499, by = 1), h = NULL, kern = gaussK)
print(k_opt1)
deri_est1 = DerivEstQuotient(Y = Y_1, X = X_1, k = k_opt1)

h_opt1 = RSSBandwidth(Y = deri_est1$Y_deri, U = deri_est1$U_ord, k = k_opt1, h_range = seq(0.04, 0.1, by = 0.005), deg = 3)
print(h_opt1)
h_opt1 = h_opt1*1.01431

qry_range = seq(k_opt1 + 1, n-k_opt1, by = 1)
u_qry = seq(min(deri_est1$U_ord[qry_range]), max(deri_est1$U_ord[qry_range]), length.out = 100)
deri_true1 = -2*pi*sin(4*pi*u_qry) + 3/(3*u_qry + 4)

Y_deriv_sm1 = LocalPolyReg(Y = deri_est1$Y_deri, X = deri_est1$U_ord, xeval = deri_est1$U_ord, h = h_opt1, kern = gaussK, deg = 3, deriv_ord = 0)
```

```{r}
pdf("./Figures/sim1_deriv_u.pdf", width = 8.5, height = 6.3)
par(mar = c(4, 6, 0.2, 1))  
plot(deri_est1$U_ord[qry_range], deri_est1$Y_deri[qry_range], col="blue", pch=20, xlab = "U", ylab = TeX("$\\hat{Y}^{(1)}, \\hat{r}^{(1)}(u)$"), cex.lab=2, cex.axis=2)
lines(deri_est1$U_ord[qry_range], y = Y_deriv_sm1[qry_range], col="red", lty="dashed", lwd=5)
legend(-0.01, 8.6, legend=c(TeX("Noisy $\\hat{r}^{(1)}(x)$"), TeX("Smoothed $\\hat{r}^{(1)}(x)$")), fill=c("blue", "red"), cex=1.5)
```

```{r}
Y_deriv_trans1 = Y_deriv_sm1 * deri_est1$den_ord
Y_deriv_noisy1 = deri_est1$Y_deri * deri_est1$den_ord

x_qry = seq(min(deri_est1$X_ord[qry_range]), max(deri_est1$X_ord[qry_range]), length.out = 100)
True_deriv1 = -2*pi*sin(4*pi*x_qry) + 3/(3*x_qry+4)

pdf("./Figures/sim1_deriv_x_rep.pdf", width = 8, height = 6)
par(mar = c(4, 5.5, 0.2, 1))
plot(deri_est1$X_ord[qry_range], Y_deriv_trans1[qry_range], pch=16, xlab = "X", ylab = TeX("$m'(x), \\hat{m}'(x)$"), col="blue", cex.lab=2, cex.axis=2, cex=0.7)
lines(x_qry, True_deriv1, col="black", lwd=5)
legend(-0.02, 7.7, legend=c(TeX("Smoothed $\\hat{m}'(x)$"), "True derivative"), fill=c("blue", "black"), cex=1.5)
```

