---
title: "Time Comparison Study"
author: "Yikun Zhang"
date: "2023-05-23"
output: html_document
---

```{r}
library(ks)
library(locpol)
library(ggplot2)
library(latex2exp)
library(pspline)

source('derivative_estimation_quotients.R')
source('kernel_derivative_estimator.R')
```

```{r}
m3Deriv = function(x_qry){
  res = (1-2*x_qry)*sin(2.1*pi/(x_qry + 0.05))/(2*sqrt(x_qry*(1-x_qry))) - 2.1*pi*sqrt(x_qry*(1-x_qry))*cos(2.1*pi/(x_qry + 0.05))/((x_qry + 0.05)^2)
  return(res)
}

n = 700
B = 100
time_locpol2 = numeric(B)
time_locpol3 = numeric(B)
time_locpol4 = numeric(B)
time_psp = numeric(B)
time_GM = numeric(B)
time_NWVar = numeric(B)
time_proposed = numeric(B)

set.seed(123)
for(b in 1:B){
  X_3 = runif(n, min = 0.25, max = 1)
  m_3 = sqrt(X_3*(1 - X_3))*sin((2.1*pi)/(X_3 + 0.05))
  eps3 = rnorm(n, mean = 0, sd = 0.2)
  Y_3 = m_3 + eps3

  # locpol
  start_time = Sys.time()
  dat3 = data.frame(X = X_3, Y = Y_3)
  Y_locpol2 = locpol(Y ~ X, data = dat3, kernel = gaussK, xeval = X_3, deg = 2)
  time_locpol2[b] = as.numeric(Sys.time() - start_time)
  
  start_time = Sys.time()
  dat3 = data.frame(X = X_3, Y = Y_3)
  Y_locpol3 = locpol(Y ~ X, data = dat3, kernel = gaussK, xeval = X_3, deg = 3)
  time_locpol3[b] = as.numeric(Sys.time() - start_time)
  
  start_time = Sys.time()
  dat3 = data.frame(X = X_3, Y = Y_3)
  Y_locpol4 = locpol(Y ~ X, data = dat3, kernel = gaussK, xeval = X_3, deg = 4)
  time_locpol4[b] = as.numeric(Sys.time() - start_time)

  # pspline
  start_time = Sys.time()
  Y_pspline = sm.spline(x = sort(X_3), y = Y_3[order(X_3)], norder = 2)
  Y_psp_deriv = predict(Y_pspline, xarg = sort(X_3), nderiv = 1)
  time_psp[b] = as.numeric(Sys.time() - start_time)

  # Gasser-Muller derivative estimator
  start_time = Sys.time()
  Y_gm_deriv = GasserMullerEst(Y_3, X_3, xeval = sort(X_3), h = NULL, kern = gaussK, deriv_ord = 1)
  time_GM[b] = as.numeric(Sys.time() - start_time)

  # Variant of Nadaraya-Watson derivative estimator
  start_time = Sys.time()
  Y_varNW_deriv = NWVarEst(Y_3, X_3, xeval = sort((X_3)), h_reg = NULL, h_den = NULL, kern = gaussDeriv, deriv_ord = 1)
  time_NWVar[b] = as.numeric(Sys.time() - start_time)
  
  # Proposed first-order derivative estimator
  start_time = Sys.time()
  U_3 = kcde(X_3, eval.points = X_3, tail.flag = "lower.tail")$estimate
  k_opt3 = OptK(Y = Y_3, U = U_3, k_range = NULL, h = NULL, kern = gaussK)
  deri_est3 = DerivEstQuotient(Y = Y_3, X = X_3, k = k_opt3)
  
  h_opt3 = RSSBandwidth(Y = deri_est3$Y_deri, U = deri_est3$U_ord, k = k_opt3, 
                        h_range = seq(0.03, 0.07, by = 0.005), deg = 3)
  h_opt3 = h_opt3*1.01431
  
  qry_range = seq(k_opt3 + 1, n-k_opt3, by = 1)
  Y_deriv_sm3 = LocalPolyReg(Y = deri_est3$Y_deri[qry_range],
                             X = deri_est3$U_ord[qry_range],
                             xeval = deri_est3$U_ord, h = h_opt3,
                             kern = gaussK, deg = 3, deriv_ord = 0)
  # Y_deriv_sm3 = LocalPolyReg(Y = deri_est3$Y_deri, X = deri_est3$U_ord, 
  #                            xeval = deri_est3$U_ord, h = h_opt3, 
  #                            kern = gaussK, deg = 3, deriv_ord = 0)
  Y_deriv_trans3 = Y_deriv_sm3 * deri_est3$den_ord
  time_proposed[b] = as.numeric(Sys.time() - start_time)
}


time_df = data.frame(locpol2 = time_locpol2, 
                     locpol3 = time_locpol3, 
                     locpol4 = time_locpol4, 
                     psplines = time_psp, 
                     Gasser_Muller = time_GM, 
                     NW_Var = time_NWVar, 
                     proposed_est = time_proposed)
write.csv(time_df, "./time_comp.csv", row.names = FALSE)
```

```{r}
time_df1 = read.csv("./time_comp.csv", header = TRUE)
time_df1$proposed = time_df1$proposed_est
time_df1 = time_df1[c("locpol2", "locpol3", "locpol4", "psplines", "Gasser_Muller", "NW_Var", "proposed")]
boxplot(time_df1, ylab="Elapsed time (second)")
```

```{r}
pdf("./Figures/time_comp.pdf", width = 8, height = 6)
par(mar = c(5, 5, 0.8, 0.8))
boxplot(time_df1[order(colMeans(time_df1[sapply(time_df1, is.numeric)]))], ylab="Elapsed time (second)", cex.axis=1.6, cex.lab=1.7, col = NULL, varwidth = TRUE, boxlwd = 2, xaxt = "n")
tick = seq_along(names(sort(colMeans(time_df1[sapply(time_df1, is.numeric)]))))
axis(1, at = tick, labels = FALSE)
text(tick, par("usr")[3] - 4, names(sort(colMeans(time_df1[sapply(time_df1, is.numeric)]))), srt = 45, xpd = TRUE)
```

